name: pharmascan_app
description: A Flutter app to scan medicines and show info (starter).
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  postgrest: ^2.4.2
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  mobile_scanner: ^6.0.2
  google_mlkit_text_recognition: ^0.12.0
  easy_localization: ^3.0.6
  intl: 0.20.2
  image_picker: ^0.8.7+5
  shared_preferences: ^2.0.15
  path_provider: ^2.1.3
  supabase_flutter: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/data/medicines.json